TOPICS_SEED = [
    {
        "name": "Arrays & Hashing",
        "slug": "arrays-hashing",
        "description": "Core array manipulation and hash map patterns",
        "problems": [
            {"leetcode_id": 217, "title": "Contains Duplicate", "slug": "contains-duplicate", "difficulty": "Easy", "companies": ["Amazon", "Microsoft"]},
            {"leetcode_id": 242, "title": "Valid Anagram", "slug": "valid-anagram", "difficulty": "Easy", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 1, "title": "Two Sum", "slug": "two-sum", "difficulty": "Easy", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 49, "title": "Group Anagrams", "slug": "group-anagrams", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 347, "title": "Top K Frequent Elements", "slug": "top-k-frequent-elements", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 238, "title": "Product of Array Except Self", "slug": "product-of-array-except-self", "difficulty": "Medium", "companies": ["Amazon", "Microsoft"]},
            {"leetcode_id": 36, "title": "Valid Sudoku", "slug": "valid-sudoku", "difficulty": "Medium", "companies": ["Amazon"]},
            {"leetcode_id": 128, "title": "Longest Consecutive Sequence", "slug": "longest-consecutive-sequence", "difficulty": "Medium", "companies": ["Google", "Meta"]},
        ],
    },
    {
        "name": "Two Pointers",
        "slug": "two-pointers",
        "description": "Problems solved efficiently with two pointer technique",
        "problems": [
            {"leetcode_id": 125, "title": "Valid Palindrome", "slug": "valid-palindrome", "difficulty": "Easy", "companies": ["Amazon", "Meta"]},
            {"leetcode_id": 167, "title": "Two Sum II", "slug": "two-sum-ii-input-array-is-sorted", "difficulty": "Medium", "companies": ["Amazon"]},
            {"leetcode_id": 15, "title": "3Sum", "slug": "3sum", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 11, "title": "Container With Most Water", "slug": "container-with-most-water", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 42, "title": "Trapping Rain Water", "slug": "trapping-rain-water", "difficulty": "Hard", "companies": ["Amazon", "Google", "Meta"]},
        ],
    },
    {
        "name": "Sliding Window",
        "slug": "sliding-window",
        "description": "Optimal subarray and substring problems",
        "problems": [
            {"leetcode_id": 121, "title": "Best Time to Buy and Sell Stock", "slug": "best-time-to-buy-and-sell-stock", "difficulty": "Easy", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 3, "title": "Longest Substring Without Repeating Characters", "slug": "longest-substring-without-repeating-characters", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 424, "title": "Longest Repeating Character Replacement", "slug": "longest-repeating-character-replacement", "difficulty": "Medium", "companies": ["Google"]},
            {"leetcode_id": 567, "title": "Permutation in String", "slug": "permutation-in-string", "difficulty": "Medium", "companies": ["Amazon", "Microsoft"]},
            {"leetcode_id": 76, "title": "Minimum Window Substring", "slug": "minimum-window-substring", "difficulty": "Hard", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 239, "title": "Sliding Window Maximum", "slug": "sliding-window-maximum", "difficulty": "Hard", "companies": ["Amazon", "Google"]},
        ],
    },
    {
        "name": "Stack",
        "slug": "stack",
        "description": "Stack-based problems including monotonic stack",
        "problems": [
            {"leetcode_id": 20, "title": "Valid Parentheses", "slug": "valid-parentheses", "difficulty": "Easy", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 155, "title": "Min Stack", "slug": "min-stack", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 150, "title": "Evaluate Reverse Polish Notation", "slug": "evaluate-reverse-polish-notation", "difficulty": "Medium", "companies": ["Amazon"]},
            {"leetcode_id": 22, "title": "Generate Parentheses", "slug": "generate-parentheses", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 739, "title": "Daily Temperatures", "slug": "daily-temperatures", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 853, "title": "Car Fleet", "slug": "car-fleet", "difficulty": "Medium", "companies": []},
            {"leetcode_id": 84, "title": "Largest Rectangle in Histogram", "slug": "largest-rectangle-in-histogram", "difficulty": "Hard", "companies": ["Amazon", "Google"]},
        ],
    },
    {
        "name": "Binary Search",
        "slug": "binary-search",
        "description": "Binary search on sorted arrays and search spaces",
        "problems": [
            {"leetcode_id": 704, "title": "Binary Search", "slug": "binary-search", "difficulty": "Easy", "companies": ["Amazon"]},
            {"leetcode_id": 74, "title": "Search a 2D Matrix", "slug": "search-a-2d-matrix", "difficulty": "Medium", "companies": ["Amazon", "Microsoft"]},
            {"leetcode_id": 875, "title": "Koko Eating Bananas", "slug": "koko-eating-bananas", "difficulty": "Medium", "companies": ["Google"]},
            {"leetcode_id": 153, "title": "Find Minimum in Rotated Sorted Array", "slug": "find-minimum-in-rotated-sorted-array", "difficulty": "Medium", "companies": ["Amazon", "Microsoft"]},
            {"leetcode_id": 33, "title": "Search in Rotated Sorted Array", "slug": "search-in-rotated-sorted-array", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft"]},
            {"leetcode_id": 981, "title": "Time Based Key-Value Store", "slug": "time-based-key-value-store", "difficulty": "Medium", "companies": ["Google"]},
            {"leetcode_id": 4, "title": "Median of Two Sorted Arrays", "slug": "median-of-two-sorted-arrays", "difficulty": "Hard", "companies": ["Amazon", "Google"]},
        ],
    },
    {
        "name": "Linked List",
        "slug": "linked-list",
        "description": "Singly and doubly linked list manipulation",
        "problems": [
            {"leetcode_id": 206, "title": "Reverse Linked List", "slug": "reverse-linked-list", "difficulty": "Easy", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 21, "title": "Merge Two Sorted Lists", "slug": "merge-two-sorted-lists", "difficulty": "Easy", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 143, "title": "Reorder List", "slug": "reorder-list", "difficulty": "Medium", "companies": ["Amazon"]},
            {"leetcode_id": 19, "title": "Remove Nth Node From End of List", "slug": "remove-nth-node-from-end-of-list", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 138, "title": "Copy List with Random Pointer", "slug": "copy-list-with-random-pointer", "difficulty": "Medium", "companies": ["Amazon", "Microsoft"]},
            {"leetcode_id": 2, "title": "Add Two Numbers", "slug": "add-two-numbers", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 141, "title": "Linked List Cycle", "slug": "linked-list-cycle", "difficulty": "Easy", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 287, "title": "Find the Duplicate Number", "slug": "find-the-duplicate-number", "difficulty": "Medium", "companies": ["Amazon"]},
            {"leetcode_id": 146, "title": "LRU Cache", "slug": "lru-cache", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 23, "title": "Merge K Sorted Lists", "slug": "merge-k-sorted-lists", "difficulty": "Hard", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 25, "title": "Reverse Nodes in k-Group", "slug": "reverse-nodes-in-k-group", "difficulty": "Hard", "companies": ["Amazon", "Microsoft"]},
        ],
    },
    {
        "name": "Trees",
        "slug": "trees",
        "description": "Binary trees, BSTs, traversals, and tree construction",
        "problems": [
            {"leetcode_id": 226, "title": "Invert Binary Tree", "slug": "invert-binary-tree", "difficulty": "Easy", "companies": ["Google", "Amazon"]},
            {"leetcode_id": 104, "title": "Maximum Depth of Binary Tree", "slug": "maximum-depth-of-binary-tree", "difficulty": "Easy", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 543, "title": "Diameter of Binary Tree", "slug": "diameter-of-binary-tree", "difficulty": "Easy", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 110, "title": "Balanced Binary Tree", "slug": "balanced-binary-tree", "difficulty": "Easy", "companies": ["Amazon"]},
            {"leetcode_id": 100, "title": "Same Tree", "slug": "same-tree", "difficulty": "Easy", "companies": ["Amazon"]},
            {"leetcode_id": 572, "title": "Subtree of Another Tree", "slug": "subtree-of-another-tree", "difficulty": "Easy", "companies": ["Amazon"]},
            {"leetcode_id": 235, "title": "Lowest Common Ancestor of BST", "slug": "lowest-common-ancestor-of-a-binary-search-tree", "difficulty": "Medium", "companies": ["Amazon", "Microsoft"]},
            {"leetcode_id": 102, "title": "Binary Tree Level Order Traversal", "slug": "binary-tree-level-order-traversal", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 199, "title": "Binary Tree Right Side View", "slug": "binary-tree-right-side-view", "difficulty": "Medium", "companies": ["Amazon", "Meta"]},
            {"leetcode_id": 1448, "title": "Count Good Nodes in Binary Tree", "slug": "count-good-nodes-in-binary-tree", "difficulty": "Medium", "companies": []},
            {"leetcode_id": 98, "title": "Validate Binary Search Tree", "slug": "validate-binary-search-tree", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 230, "title": "Kth Smallest Element in BST", "slug": "kth-smallest-element-in-a-bst", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 105, "title": "Construct Binary Tree from Preorder and Inorder", "slug": "construct-binary-tree-from-preorder-and-inorder-traversal", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 124, "title": "Binary Tree Maximum Path Sum", "slug": "binary-tree-maximum-path-sum", "difficulty": "Hard", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 297, "title": "Serialize and Deserialize Binary Tree", "slug": "serialize-and-deserialize-binary-tree", "difficulty": "Hard", "companies": ["Amazon", "Google", "Meta"]},
        ],
    },
    {
        "name": "Heap / Priority Queue",
        "slug": "heap-priority-queue",
        "description": "Min/max heap problems and K-way operations",
        "problems": [
            {"leetcode_id": 703, "title": "Kth Largest Element in a Stream", "slug": "kth-largest-element-in-a-stream", "difficulty": "Easy", "companies": ["Amazon"]},
            {"leetcode_id": 1046, "title": "Last Stone Weight", "slug": "last-stone-weight", "difficulty": "Easy", "companies": []},
            {"leetcode_id": 973, "title": "K Closest Points to Origin", "slug": "k-closest-points-to-origin", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 215, "title": "Kth Largest Element in an Array", "slug": "kth-largest-element-in-an-array", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 621, "title": "Task Scheduler", "slug": "task-scheduler", "difficulty": "Medium", "companies": ["Amazon"]},
            {"leetcode_id": 355, "title": "Design Twitter", "slug": "design-twitter", "difficulty": "Medium", "companies": ["Amazon"]},
            {"leetcode_id": 295, "title": "Find Median from Data Stream", "slug": "find-median-from-data-stream", "difficulty": "Hard", "companies": ["Amazon", "Google"]},
        ],
    },
    {
        "name": "Backtracking",
        "slug": "backtracking",
        "description": "Exhaustive search with pruning",
        "problems": [
            {"leetcode_id": 78, "title": "Subsets", "slug": "subsets", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 39, "title": "Combination Sum", "slug": "combination-sum", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 46, "title": "Permutations", "slug": "permutations", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 90, "title": "Subsets II", "slug": "subsets-ii", "difficulty": "Medium", "companies": []},
            {"leetcode_id": 40, "title": "Combination Sum II", "slug": "combination-sum-ii", "difficulty": "Medium", "companies": []},
            {"leetcode_id": 79, "title": "Word Search", "slug": "word-search", "difficulty": "Medium", "companies": ["Amazon", "Microsoft"]},
            {"leetcode_id": 131, "title": "Palindrome Partitioning", "slug": "palindrome-partitioning", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 17, "title": "Letter Combinations of a Phone Number", "slug": "letter-combinations-of-a-phone-number", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 51, "title": "N-Queens", "slug": "n-queens", "difficulty": "Hard", "companies": ["Amazon", "Google"]},
        ],
    },
    {
        "name": "Graphs",
        "slug": "graphs",
        "description": "Graph traversal, connected components, and shortest paths",
        "problems": [
            {"leetcode_id": 200, "title": "Number of Islands", "slug": "number-of-islands", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 133, "title": "Clone Graph", "slug": "clone-graph", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 695, "title": "Max Area of Island", "slug": "max-area-of-island", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 417, "title": "Pacific Atlantic Water Flow", "slug": "pacific-atlantic-water-flow", "difficulty": "Medium", "companies": ["Google"]},
            {"leetcode_id": 130, "title": "Surrounded Regions", "slug": "surrounded-regions", "difficulty": "Medium", "companies": []},
            {"leetcode_id": 994, "title": "Rotting Oranges", "slug": "rotting-oranges", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 286, "title": "Walls and Gates", "slug": "walls-and-gates", "difficulty": "Medium", "companies": ["Meta"]},
            {"leetcode_id": 207, "title": "Course Schedule", "slug": "course-schedule", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 210, "title": "Course Schedule II", "slug": "course-schedule-ii", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 684, "title": "Redundant Connection", "slug": "redundant-connection", "difficulty": "Medium", "companies": []},
            {"leetcode_id": 323, "title": "Number of Connected Components", "slug": "number-of-connected-components-in-an-undirected-graph", "difficulty": "Medium", "companies": ["Amazon", "LinkedIn"]},
            {"leetcode_id": 261, "title": "Graph Valid Tree", "slug": "graph-valid-tree", "difficulty": "Medium", "companies": ["Google", "LinkedIn"]},
            {"leetcode_id": 127, "title": "Word Ladder", "slug": "word-ladder", "difficulty": "Hard", "companies": ["Amazon", "Google", "Meta"]},
        ],
    },
    {
        "name": "Dynamic Programming 1D",
        "slug": "dynamic-programming-1d",
        "description": "1D DP — climbing stairs, house robber, subsequences",
        "problems": [
            {"leetcode_id": 70, "title": "Climbing Stairs", "slug": "climbing-stairs", "difficulty": "Easy", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 746, "title": "Min Cost Climbing Stairs", "slug": "min-cost-climbing-stairs", "difficulty": "Easy", "companies": []},
            {"leetcode_id": 198, "title": "House Robber", "slug": "house-robber", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 213, "title": "House Robber II", "slug": "house-robber-ii", "difficulty": "Medium", "companies": []},
            {"leetcode_id": 5, "title": "Longest Palindromic Substring", "slug": "longest-palindromic-substring", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft"]},
            {"leetcode_id": 647, "title": "Palindromic Substrings", "slug": "palindromic-substrings", "difficulty": "Medium", "companies": []},
            {"leetcode_id": 91, "title": "Decode Ways", "slug": "decode-ways", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 322, "title": "Coin Change", "slug": "coin-change", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft"]},
            {"leetcode_id": 152, "title": "Maximum Product Subarray", "slug": "maximum-product-subarray", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 139, "title": "Word Break", "slug": "word-break", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 300, "title": "Longest Increasing Subsequence", "slug": "longest-increasing-subsequence", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft"]},
            {"leetcode_id": 416, "title": "Partition Equal Subset Sum", "slug": "partition-equal-subset-sum", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
        ],
    },
    {
        "name": "Dynamic Programming 2D",
        "slug": "dynamic-programming-2d",
        "description": "2D DP — grids, strings, knapsack",
        "problems": [
            {"leetcode_id": 62, "title": "Unique Paths", "slug": "unique-paths", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft"]},
            {"leetcode_id": 1143, "title": "Longest Common Subsequence", "slug": "longest-common-subsequence", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft"]},
            {"leetcode_id": 309, "title": "Best Time to Buy and Sell Stock with Cooldown", "slug": "best-time-to-buy-and-sell-stock-with-cooldown", "difficulty": "Medium", "companies": []},
            {"leetcode_id": 518, "title": "Coin Change II", "slug": "coin-change-ii", "difficulty": "Medium", "companies": []},
            {"leetcode_id": 494, "title": "Target Sum", "slug": "target-sum", "difficulty": "Medium", "companies": ["Amazon"]},
            {"leetcode_id": 97, "title": "Interleaving String", "slug": "interleaving-string", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 329, "title": "Longest Increasing Path in a Matrix", "slug": "longest-increasing-path-in-a-matrix", "difficulty": "Hard", "companies": ["Google"]},
            {"leetcode_id": 115, "title": "Distinct Subsequences", "slug": "distinct-subsequences", "difficulty": "Hard", "companies": []},
            {"leetcode_id": 72, "title": "Edit Distance", "slug": "edit-distance", "difficulty": "Hard", "companies": ["Amazon", "Google", "Microsoft"]},
            {"leetcode_id": 312, "title": "Burst Balloons", "slug": "burst-balloons", "difficulty": "Hard", "companies": ["Google"]},
            {"leetcode_id": 10, "title": "Regular Expression Matching", "slug": "regular-expression-matching", "difficulty": "Hard", "companies": ["Amazon", "Google", "Meta"]},
        ],
    },
    {
        "name": "Greedy",
        "slug": "greedy",
        "description": "Locally optimal choices leading to global optimum",
        "problems": [
            {"leetcode_id": 53, "title": "Maximum Subarray", "slug": "maximum-subarray", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft"]},
            {"leetcode_id": 55, "title": "Jump Game", "slug": "jump-game", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft"]},
            {"leetcode_id": 45, "title": "Jump Game II", "slug": "jump-game-ii", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 134, "title": "Gas Station", "slug": "gas-station", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 846, "title": "Hand of Straights", "slug": "hand-of-straights", "difficulty": "Medium", "companies": []},
            {"leetcode_id": 1899, "title": "Merge Triplets to Form Target", "slug": "merge-triplets-to-form-target-triplet", "difficulty": "Medium", "companies": []},
            {"leetcode_id": 763, "title": "Partition Labels", "slug": "partition-labels", "difficulty": "Medium", "companies": ["Amazon"]},
            {"leetcode_id": 678, "title": "Valid Parenthesis String", "slug": "valid-parenthesis-string", "difficulty": "Medium", "companies": []},
        ],
    },
    {
        "name": "Intervals",
        "slug": "intervals",
        "description": "Interval merging, insertion, and scheduling",
        "problems": [
            {"leetcode_id": 57, "title": "Insert Interval", "slug": "insert-interval", "difficulty": "Medium", "companies": ["Google", "LinkedIn"]},
            {"leetcode_id": 56, "title": "Merge Intervals", "slug": "merge-intervals", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 435, "title": "Non-overlapping Intervals", "slug": "non-overlapping-intervals", "difficulty": "Medium", "companies": []},
            {"leetcode_id": 252, "title": "Meeting Rooms", "slug": "meeting-rooms", "difficulty": "Easy", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 253, "title": "Meeting Rooms II", "slug": "meeting-rooms-ii", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"]},
            {"leetcode_id": 1851, "title": "Minimum Interval to Include Each Query", "slug": "minimum-interval-to-include-each-query", "difficulty": "Hard", "companies": []},
        ],
    },
    {
        "name": "Tries",
        "slug": "tries",
        "description": "Prefix tree construction and search",
        "problems": [
            {"leetcode_id": 208, "title": "Implement Trie", "slug": "implement-trie-prefix-tree", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft"]},
            {"leetcode_id": 211, "title": "Design Add and Search Words Data Structure", "slug": "design-add-and-search-words-data-structure", "difficulty": "Medium", "companies": ["Amazon"]},
            {"leetcode_id": 212, "title": "Word Search II", "slug": "word-search-ii", "difficulty": "Hard", "companies": ["Amazon", "Google", "Microsoft"]},
        ],
    },
    {
        "name": "Bit Manipulation",
        "slug": "bit-manipulation",
        "description": "XOR, AND, OR tricks and bit counting",
        "problems": [
            {"leetcode_id": 136, "title": "Single Number", "slug": "single-number", "difficulty": "Easy", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 191, "title": "Number of 1 Bits", "slug": "number-of-1-bits", "difficulty": "Easy", "companies": ["Amazon"]},
            {"leetcode_id": 338, "title": "Counting Bits", "slug": "counting-bits", "difficulty": "Easy", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 190, "title": "Reverse Bits", "slug": "reverse-bits", "difficulty": "Easy", "companies": ["Amazon"]},
            {"leetcode_id": 268, "title": "Missing Number", "slug": "missing-number", "difficulty": "Easy", "companies": ["Amazon", "Google", "Microsoft"]},
            {"leetcode_id": 371, "title": "Sum of Two Integers", "slug": "sum-of-two-integers", "difficulty": "Medium", "companies": ["Amazon"]},
            {"leetcode_id": 7, "title": "Reverse Integer", "slug": "reverse-integer", "difficulty": "Medium", "companies": ["Amazon"]},
        ],
    },
    {
        "name": "Math & Geometry",
        "slug": "math-geometry",
        "description": "Number theory, geometry, and simulation",
        "problems": [
            {"leetcode_id": 202, "title": "Happy Number", "slug": "happy-number", "difficulty": "Easy", "companies": ["Amazon"]},
            {"leetcode_id": 66, "title": "Plus One", "slug": "plus-one", "difficulty": "Easy", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 50, "title": "Pow(x, n)", "slug": "powx-n", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft"]},
            {"leetcode_id": 43, "title": "Multiply Strings", "slug": "multiply-strings", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
            {"leetcode_id": 2013, "title": "Detect Squares", "slug": "detect-squares", "difficulty": "Medium", "companies": []},
            {"leetcode_id": 54, "title": "Spiral Matrix", "slug": "spiral-matrix", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft"]},
            {"leetcode_id": 48, "title": "Rotate Image", "slug": "rotate-image", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft"]},
            {"leetcode_id": 73, "title": "Set Matrix Zeroes", "slug": "set-matrix-zeroes", "difficulty": "Medium", "companies": ["Amazon", "Google"]},
        ],
    },
]